### ISSUE TITLE
Perform joint calling when calling variants

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#385]
Rather than calling samples individually, call together. We can bring in the issue in #317 as well here. If we have the following command:

freebayes -f <reference.fa> -r <region> -b proband.bam -b mother.bam -b father.bam | vt normalize -r <reference.fa> -o + - | vt subset -s <samples.txt> -o + + | vt filter -f "" -t "IOBIO" -d "Variants called by iobio" + 

This will call on all samples, then normalize, subset on all samples (this will get rid of low quality cases where no sample is actually called as having the alt) and then add IOBIO in the filter column. The -o + in the vt commands outputs bcf and vt commands that have bcf as stdin use + rather than - to denote the input.

With this command, all samples that are homozygous reference will have the details in the genotype field so we will be able to populate the AC fields.

**Comment by tonydisera** [comment]
Hi Al, 

I'm confused about the usage for the vt subset after joint calling:

vt subset -s -o + + 

Why aren't we sending in a list of sample names if we use the -s arg?  Also, I didn't see -o as an argument for vt subset...

**Comment by AlistairNWard** [comment]
Sorry, that's a mistake on my part, -s should be followed by a file containing all the sample names. There will be cases where all three samples have the 0/0 genotype and the subset command will get rid of them.

The -o + + just helps speed things up, so there's no reason to omit, but can do if you like. Note that you can't just omit it from the command line above though. The input to vt normalize is -, the vcf stream from freebayes, but in the command above, the output of normalize is bcf (-o +). This means that the input to subset is listed as +. We also output again as bcf (-o +) and again the input to vt filter is '+', the bcf stream. I'm not totally sure how the IOBIO commands are put together, but if there is a -o + from any tool, the following tool must have '+' as the input. We can just switch them all to '-' and the streams will then bc vcf not bcf. Make any sense at all?

**Comment by tonydisera** [comment]
Hi Al,

You may already have an issue on this -- the freebayes variants are getting 'FLAGGED for LOW QUALITY' because of the filter field = '.'   What would you think about this?  Have the code set the filter flag to 'PASS' if the quality is > 1?

**Comment by tonydisera** [comment]
To test calling variants (to get some deltas with loaded variants):
http://localhost/gene.iobio/?rel0=proband&rel1=mother&rel2=father&name0=NA12878&bam0=https://s3.amazonaws.com/iobio/NA12892/NA12892.autsome.bam&sample1=NA12892&name1=NA12892&sample2=NA12891&name2=NA12891&affectedSibs=&unaffectedSibs=&genes=BRCA1,RAI1,PDHA1&gene=RAI1&sample0=NA12878&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/NA12892/NA12892.autsome.bam&bam1=https://s3.amazonaws.com/iobio/NA12891/NA12891.autsome.bam&vcf1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&vcf2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz

**Comment by AlistairNWard** [comment]
Look at the full command line in the first post for this issue. The last part of the stream runs through vt filter and tags all called variants with "IOBIO".

**Comment by tonydisera** [comment]
Ah, I see. I didn't see a filter of QUAL > 1.  So the -f '' does the trick, huh?

**Comment by AlistairNWard** [comment]
The -f "" basically means apply no actual filter, so every variant will pass this. Then the tag "IOBIO" will be applied to all the called variants and the -d just adds a line to the header (we don't need the header updated, but vt requires the value to be set).

**Comment by AlistairNWard** [comment]
I would be loathe to mark anything as PASS, since the uploaded calls will likely be marked with this. If we also mark our called variants with PASS, the implication would be that the uploaded and called variants that PASS, conform to the same set of filters, which is not the case. So, I would be happy to change to -f "QUAL > 1" instead of -f "", but I would leave -t "IOBIO". Then anything that fails will be '.' and be greyed out, but there will still be a distinction between uploaded and called variants, allowing the user to apply filters on the different sets.

**Comment by tonydisera** [comment]
I like that approach.  :-)

**Comment by tonydisera** [comment]
But I refuse to implement it that way.

**Comment by tonydisera** [comment]
Hi Al -

I have a question about the filter:
 vt filter -f "" -t "IOBIO" -d "Variants called by iobio"

I didn't see this usage for vt.  Did you mean vcflib?

I was able to get this command to work:
?vcflib vcffilter -f "" -t "IOBIO"

But it the -d "Variants called by iobio" wasn't allowed.

Am I on the right track?

**Comment by tonydisera** [comment]
todo:
1. Local bam files
2. Parsing vcf records not working when only bams provided (no sample id)
3. Move code in app to variantTrioModel.

**Comment by AlistairNWard** [comment]
Nope, definitely needs to be vt. Maybe the version of vt being used is too old? But this is the command we need.

**Comment by AlistairNWard** [comment]
I ran calling on the demo data set (using nv-dev) and saw no information for the parents. I'll run this locally to see what the Freebayes call is, but either they were no calls, or the information isn't being displayed properly. I'll follow up...

**Comment by AlistairNWard** [comment]
I'm still seeing 'analyzing' appear for Mum and Dad after variant calling. Using the new tutorial data set, call variants in MYLK2:

http://nv-dev.iobio.io/gene.iobio/?rel0=proband&rel1=mother&rel2=father&genes=MYLK2&gene=MYLK2&name0=&bam0=https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam&name1=&bam1=https://s3.amazonaws.com/iobio/samples/bam/NA12892.exome.bam&name2=&bam2=https://s3.amazonaws.com/iobio/samples/bam/NA12891.exome.bam&vcf2=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz&vcf1=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz&vcf0=https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz&sample2=NA12891&sample1=NA12892&sample0=NA12878&affectedSibs=&unaffectedSibs=

We find a new variant in the proband, and nothing new in Mum and Dad, but the mousetip doesn't give us info on the parents data.

**Comment by AlistairNWard** [comment]
![screen shot 2016-10-14 at 9 19 40 am](https://cloud.githubusercontent.com/assets/523111/19388797/6070314e-91ef-11e6-9fbf-c678267f29bc.png)

**Comment by tonydisera** [comment]
Hi Al.  I'm having trouble reproducing this bug.  I'm going to put a fresh copy of gene.iobio out on nv-dev (from the dev branch).

**Comment by AlistairNWard** [comment]
I just tried this on nv-dev and it appears to have been fixed.

**Comment by tonydisera** [comment]
There have been quite a few bug fixes that I just pushed to dev, so this should probably be revalidated.

**Comment by AlistairNWard** [comment]
Still seeing "analyzing" appear sometimes.  I'm looking at GRCh38 in AIRE, using AWS GRCh38 files. There is a green variant at the far right of the cards, if you click on the variant in the proband, everything is fine, but if I click on the variant in the Mother card, the tooltip is fine, but the inspect panel is "analyzing" for the mother only.

**Comment by AlistairNWard** [comment]
<img width="208" alt="screen shot 2016-11-21 at 7 45 30 pm" src="https://cloud.githubusercontent.com/assets/523111/20506675/8fd0ee68-b023-11e6-9da5-fd78faebb83d.png">

**Comment by tonydisera** [comment]
Darn.  I will look into this today.
