### ISSUE TITLE
Fix problems with App Tour

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#527]
I've fixed the app tour for the new UI, but a number of problems still exist.  See comments below.

**Comment by tonydisera** [comment]
1. On the part where it asks you to click 'Select Data', the red box shows you where, but once you've clicked it, the box remains and looks a bit odd. Would it make sense for the box to disappear, and numbers appear next to the "Genome build", "Variants" etc. to correspond with the numbers in the instructions?

2. The next step shows you the variants. In the text, the final sentence is "The the variants...". Perhaps overdoing the the's.

3. On the ranked variants bit, it tells you to click a column to show a variant. The red box is on top of the tooltip which looks a bit odd. I think the tooltip should be on top.

4. Same box tells you that the criteria can be reordered by clicking on their respective arrows, but you need to click "Reorder" first to see these arrows. Probably need to point that out.

5. Next slide text is "For the gene BRCA2, the variant were annotated and ranked based on the canonical transcript.". "variant" should be "variants".

6. The last sentence on this slide has a spurious "the". You love just throwing a "the" in for fun.

7. This one is not tutorial specific. When you open the transcript dropdown, it can be difficult to select a transcript. If you hover over an exon in one of the alternate transcripts, the mouse arrow changes to the selection arrow and it's easy. When you're over introns, you have to hover over the very thin line. Is it possible to have the vertical height for the transcript selection set to the height of the exon across the whole transcript? Or draw invisible introns, so hovering anywhere over the transcript acts the same way as hovering over the exon?

8. When you expand the +/- on the region size, there is a spurious "display". Maybe you should change this to a "the"? Since we're not displaying DNA, maybe this should be rewritten, e.g. "Adjust this value to modify the displayed genomic region. Increasing the amount of upstream and downstream DNA analyzed increases the potential for detecting cis regulatory variants for this gene."?

9. Calling variants. An extra "the". Love it. Maybe also specifically mention BAM file. Actually, wow, there is another extra "the" in the second line as well. I'm beginning to think you're doing this on purpose!

10. Run Freebayes. Guess what? An extra "the". Now I'm laughing out loud at my desk! ("Variants are called in the real-time").

11. When you click on the variant to examine in detail, the red box is in the middle of the tooltip.

12. See our tour of bookmarks for more details. Can we provide a link? Or maybe point out where to find them.

13. When I clicked on "Select Genes", the tour automatically jumped to the next step, but I hadn't read the rest of the text and had to go back. Again, do we have a link to the Phenolyzer tour.

**Comment by tonydisera** [comment]
Getting the app tour to work with widgets on a dialog is tricky.  I can fix this, but it will take some cycles.  What would you think about reworking the tour to have the user click on the 'Load demo data' on the welcome panel instead of entering selections from the 'Select data' dialog?

**Comment by AlistairNWard** [comment]
I think it's good to have the user go through the 'Select Data' section. Maybe just lose the red box around the 'Select Data' and leave it that. No need to go to effort to add numbers to the menus.

**Comment by AlistairNWard** [comment]
On step 11, I still get the red box around the variants on top of the tooltip.

**Comment by tonydisera** [comment]
I fixed step 11.  Unfortunately, losing the box around the 'Select data' link requires some more customization of the tour javascript library. Do you think this is too confusing to leave as-is?

**Comment by AlistairNWard** [comment]
No, I think it's fine, but I see something else odd. After calling, one of the messages says "The proband variant card now shows one variant", with a box around the "1". Click Next, and the tour tells me to click a variant to lock the tooltip and the red box is sitting next to "Variants called" and is super small. Not sure why it's there!

Everything else looks good though.

**Comment by tonydisera** [comment]
I fixed the tiny box problem.

**Comment by AlistairNWard** [comment]
Hmm. I'm still seeing the tiny box. I cleared the cache and everything.

**Comment by AlistairNWard** [comment]
<img width="1314" alt="screen shot 2017-01-25 at 9 53 15 pm" src="https://cloud.githubusercontent.com/assets/523111/22318454/c126dfe2-e348-11e6-8606-be936f3c8376.png">

**Comment by tonydisera** [comment]
Give it another try.  (I need to remember that whenever I move an issue over to 'Ready to validate', I need to refresh nv-dev!)

**Comment by AlistairNWard** [comment]
Ha, yeah, that is fixed. However, in the spirit of never letting this be closed, I have a couple more comments. Sorry!

I click on ACMG56 when I'm told and they load, and I get to the final screen which says "Starting the gene.iobio tour over...". This needs rewording. If I click backwards, I see a different panel that tells me the tour is over, which should be the final message. If I click back again, I see a message about the "Import Gene Set" option, but I never saw that going forwards through the tour. I think we are auto jumping the tour message instead of requiring you to click "next" sometimes and some screens are getting skipped.

**Comment by tonydisera** [comment]
Yeah, this is the oddities of the javascript library I pulled down,  This will take some time to fix.  Are you okay waiting until after this release?

**Comment by AlistairNWard** [comment]
Totally fine. The tour is not something to hold us back.
