### ISSUE TITLE
Wrong badge assigned to gene when 'Call variants for selected gene' and clicking on standard filter buttons occurs in quick succession.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#611]
Open the demo data, and analyze all
Then call on MYLK2. Before the calling finishes, click on the filters and go through the defined filters
We don't have any called variants yet, so we only see results for loaded
Once calling has finished, redo the filters, and now there is a known pathogenic called variant
The gene badge for MYLK2 shows first in the list with a pathogenic ClinVar variant, but it is actually only likely pathogenic

![screen shot 2017-04-27 at 2 10 17 pm](https://cloud.githubusercontent.com/assets/8420103/25505453/fe247cac-2b5e-11e7-9ed3-98dd46b1187c.png)

**Comment by tonydisera** [comment]
The problem had to do with VariantCard.vcfData having data for RAI1 rather than MYLK2.  By changing methods in VariantModel to no rely on state (this.vcfData), the problem has been fixed.

**Comment by AlistairNWard** [comment]
Sorry, but I still don't think this is right. Now, the called variant is not showing any ClinVar annotation, but it is a likely pathogenic variant.

**Comment by tonydisera** [comment]
This should be fixed now.   I pushed a number of bug fixes to production tonight.

**Comment by AlistairNWard** [comment]
Fixed.
